[project]
name = "trackit_backend"
version = "0.1.0"
description = "This is the Backend of the TrackIT project"
authors = [
    {name = "Shouryan Bharote",email = "shouryanbharote888@gmail.com"}
]
license = "GNU v3"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv (>=1.2.2,<2.0.0)"
    
]
[dependency-groups]
api = [

    ]
scraper = [

    ]
dev = [

    ]
test = [
    "pytest (>=6.0.0,<7.0.0)",
    "pytest-mock",
    ]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
