from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class LLMTask(StrEnum):
    """Supported tasks for LLM operations."""

    SELECTOR_GENERATION = "selector_generation"
    SELECTOR_REPAIR = "selector_repair"
    DATA_NORMALIZATION = "data_normalization"


class LLMProvider(StrEnum):
    """Supported LLM providers."""

    GEMINI = "gemini"
    GROQ = "groq"
    OPENROUTER = "openrouter"


class TokenUsage(BaseModel):
    """Represents the token consumption for an LLM request and response."""

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    prompt_tokens: int = Field(
        ge=0,
        description="The number of tokens in the input prompt.",
    )
    completion_tokens: int = Field(
        ge=0,
        description="The number of tokens in the generated response.",
    )
    total_tokens: int = Field(
        ge=0,
        description="The total number of tokens used.",
    )


class LLMRequest(BaseModel):
    """Represents a request sent to an LLM provider."""

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    task: LLMTask = Field(
        description="The specific LLM task to perform.",
    )

    prompt: str = Field(
        min_length=1,
        description="The input prompt for the LLM.",
    )

    provider: LLMProvider = Field(
        description="The target LLM provider.",
    )

    model: str = Field(
        min_length=1,
        description="The model name to use.",
    )

    temperature: float = Field(
        default=0.0,
        ge=0.0,
        le=2.0,
        description="Controls randomness in generation.",
    )

    max_tokens: int | None = Field(
        default=None,
        ge=1,
        description="Maximum number of tokens to generate.",
    )


class LLMResponse(BaseModel):
    """Represents a response received from an LLM provider."""

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    content: str = Field(
        description="The text generated by the model.",
    )

    provider: LLMProvider = Field(
        description="The provider that processed the request.",
    )

    model: str = Field(
        min_length=1,
        description="The model that processed the request.",
    )

    usage: TokenUsage | None = Field(
        default=None,
        description="Token usage information, if available.",
    )

    response_time: float = Field(
        ge=0.0,
        description="Time taken by the provider to generate the response in seconds.",
    )