from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field

class LLMTask(StrEnum):
    """Supported tasks for LLM operations."""

    SELECTOR_GENERATION = "selector_generation"
    SELECTOR_REPAIR = "selector_repair"
    DATA_NORMALIZATION = "data_normalization"


class LLMProvider(StrEnum):
    """Supported LLM providers."""

    GEMINI = "gemini"
    GROQ = "groq"
    OPENROUTER = "openrouter"


class TokenUsage(BaseModel):
    """Represents the token consumption for an LLM request and response."""

    model_config = ConfigDict(frozen=True)

    prompt_tokens: int = Field(
        ge=0,
        description="The number of tokens in the input prompt."
    )
    completion_tokens: int = Field(
        ge=0,
        description="The number of tokens in the generated response."
    )
    total_tokens: int = Field(
        ge=0,
        description="The total number of tokens used."
    )


class LLMRequest(BaseModel):
    """Represents a request sent to an LLM provider."""

    model_config = ConfigDict(frozen=True)

    task: LLMTask = Field(
        description="The specific LLM task to perform."
    )
    prompt: str = Field(
        description="The input prompt for the LLM."
    )
    provider: LLMProvider | None = Field(
        default=None,
        description="The target LLM provider, or None to let the system choose."
    )
    model: str | None = Field(
        default=None,
        description="The specific model name to use, or None for the default."
    )
    temperature: float = Field(
        default=0.0,
        ge=0.0,
        le=2.0,
        description="Controls randomness in generation, from 0.0 to 2.0."
    )
    max_tokens: int | None = Field(
        default=None,
        ge=1,
        description="The maximum number of tokens to generate, or None for default."
    )


class LLMResponse(BaseModel):
    """Represents a response received from an LLM provider."""

    model_config = ConfigDict(frozen=True)

    content: str = Field(
        description="The text content generated by the model."
    )
    provider: LLMProvider = Field(
        description="The LLM provider that processed the request."
    )
    model: str = Field(
        description="The model name that processed the request."
    )
    usage: TokenUsage | None = Field(
        default=None,
        description="Token consumption details, or None if unavailable."
    )
    response_time: float | None = Field(
        default=None,
        ge=0.0,
        description="The duration of the request in seconds, or None if unavailable."
    )
