# shared/llm/selector_profile.py

from datetime import UTC, datetime
from enum import StrEnum

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from shared.models.enums import OpportunityField



class SelectorType(StrEnum):
    """Supported selector locator types."""

    CSS = "css"
    XPATH = "xpath"


class ExtractionType(StrEnum):
    """Supported extraction types."""

    TEXT = "text"
    ATTRIBUTE = "attribute"
    HTML = "html"
    LIST = "list"
    TABLE = "table"
    JSON = "json"



class Selector(BaseModel):
    """Represents a single selector configuration."""

    model_config = ConfigDict(frozen=True)

    type: SelectorType = Field(
        description="The selector type."
    )
    value: str = Field(
        description="The selector expression."
    )
    priority: int = Field(
        ge=1,
        description="Priority of the selector. Lower values are tried first."
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score assigned by the LLM."
    )

    wait_for: bool = Field(
        default=False,
        description="Whether the engine should wait for this selector before extracting."
    )
    timeout: int | None = Field(
        default=None,
        description="Optional selector wait timeout in milliseconds."
    )



class ExtractionField(BaseModel):
    """Represents a single field to extract from a webpage."""

    model_config = ConfigDict(frozen=True)

    name: OpportunityField = Field(
        description="The canonical opportunity field to extract."
    )
    description: str | None = Field(
        default=None,
        description="Optional description of the field."
    )
    required: bool = Field(
        default=True,
        description="Whether this field is required."
    )
    default: object | None = Field(
        default=None,
        description="Fallback value when extraction fails."
    )
    extraction_type: ExtractionType = Field(
        description="How the data should be extracted."
    )
    attribute: str | None = Field(
        default=None,
        description="Attribute name when using ATTRIBUTE extraction."
    )
    selectors: list[Selector] = Field(
        description="Ordered list of selectors from highest to lowest priority."
    )

    def primary_selector(self) -> Selector:
        """Return the selector with the highest priority (lowest priority int)."""
        return sorted(self.selectors, key=lambda s: s.priority)[0]

    def ordered_selectors(self) -> list[Selector]:
        """Return selectors ordered by priority (lowest priority int first)."""
        return sorted(self.selectors, key=lambda s: s.priority)



class GenerationMetadata(BaseModel):
    """Metadata describing how the selector profile was generated."""

    model_config = ConfigDict(frozen=True)

    llm_provider: str = Field(
        description="LLM provider used to generate the profile."
    )
    llm_model: str = Field(
        description="Model used to generate the profile."
    )
    profile_version: int = Field(
        default=1,
        ge=1,
        description="Version of the selector profile."
    )
    prompt_version: int = Field(
        default=1,
        ge=1,
        description="Version of the prompt used to generate this profile."
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp when the profile was generated."
    )
    notes: str | None = Field(
        default=None,
        description="Optional notes generated by the LLM."
    )


class SelectorProfile(BaseModel):
    """Represents a complete selector profile for a webpage."""

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    website: str = Field(
        description="Website or domain this profile belongs to."
    )
    page_type: str = Field(
        description="Page type (e.g. competitions, hackathons, events, quiz)."
    )
    fields: list[ExtractionField] = Field(
        description="Fields that should be extracted from the page."
    )
    metadata: GenerationMetadata | None = Field(
        default=None,
        description="Information about how the profile was generated."
    )