from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class SelectorType(StrEnum):
    """Supported selector types."""

    CSS = "css"
    XPATH = "xpath"


class ExtractionType(StrEnum):
    """Supported extraction types."""

    TEXT = "text"
    ATTRIBUTE = "attribute"
    HTML = "html"


class Selector(BaseModel):
    """Represents a single selector configuration."""

    model_config = ConfigDict(frozen=True)

    type: SelectorType = Field(
        description="The selector type."
    )
    value: str = Field(
        description="The selector expression."
    )
    priority: int = Field(
        ge=1,
        description="Priority of the selector. Lower values are tried first."
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score assigned by the LLM."
    )


class ExtractionField(BaseModel):
    """Represents a single field to extract from a webpage."""

    model_config = ConfigDict(frozen=True)

    name: str = Field(
        description="The name of the field."
    )
    description: str | None = Field(
        default=None,
        description="Optional description of the field."
    )
    required: bool = Field(
        default=True,
        description="Whether this field is required."
    )
    extraction_type: ExtractionType = Field(
        description="How the data should be extracted."
    )
    attribute: str | None = Field(
        default=None,
        description="Attribute name when using ATTRIBUTE extraction."
    )
    selectors: list[Selector] = Field(
        description="Ordered list of selectors from highest to lowest priority."
    )


class GenerationMetadata(BaseModel):
    """Metadata describing how the selector profile was generated."""

    model_config = ConfigDict(frozen=True)

    llm_provider: str = Field(
        description="LLM provider used to generate the profile."
    )
    llm_model: str = Field(
        description="Model used to generate the profile."
    )
    profile_version: int = Field(
        default=1,
        ge=1,
        description="Version of the selector profile."
    )
    prompt_version: int = Field(
        default=1,
        ge=1,
        description="Version of the prompt used to generate this profile."
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp when the profile was generated."
    )
    notes: str | None = Field(
        default=None,
        description="Optional notes generated by the LLM."
    )


class SelectorProfile(BaseModel):
    """Represents a complete selector profile for a webpage."""

    model_config = ConfigDict(frozen=True)

    website: str = Field(
        description="Website or domain this profile belongs to."
    )
    page_type: str = Field(
        description="Page type (e.g. competitions, hackathons, events, quiz)."
    )
    fields: list[ExtractionField] = Field(
        description="Fields that should be extracted from the page."
    )
    metadata: GenerationMetadata = Field(
        description="Information about how the profile was generated."
    )